/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ReentrancyGuardTransient,
  ReentrancyGuardTransientInterface,
} from "../../../../@openzeppelin/contracts/utils/ReentrancyGuardTransient";

const _abi = [
  {
    inputs: [],
    name: "ReentrancyGuardReentrantCall",
    type: "error",
  },
] as const;

export class ReentrancyGuardTransient__factory {
  static readonly abi = _abi;
  static createInterface(): ReentrancyGuardTransientInterface {
    return new Interface(_abi) as ReentrancyGuardTransientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyGuardTransient {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ReentrancyGuardTransient;
  }
}
