/**
 * Preview landing — the page each pre-seeded kickabout player lands on.
 *
 *   /preview/<token>
 *
 * Renders the player's twin (avatar + last week's session stats) without
 * requiring wallet sign-in. The token is the player's User.walletAddress,
 * generated by scripts/seed-kickabout-session.ts. The page is the demo
 * surface — keeps the friction to zero, makes the wedge legible in the
 * first 5 seconds.
 *
 * If the token is invalid, we show a friendly empty state pointing back
 * to the main site.
 */

import React from 'react';
import { notFound } from 'next/navigation';
import { PrismaClient } from '@prisma/client';
import Link from 'next/link';

const prisma = new PrismaClient();

interface PageProps {
  params: Promise<{ token: string }>;
}

// Match the V3 palette for inline styling
const PALETTE = {
  cream: '#f0e8d6',
  ink: '#0a0a0a',
  inkLight: '#3a3a3a',
  red: '#c91022',
  navy: '#1c3a5e',
  sage: '#4a7549',
  mustard: '#d4a437',
};

function deriveInitials(name: string): string {
  return name
    .split(/\s+/)
    .map((p) => p[0])
    .join('')
    .slice(0, 2)
    .toUpperCase();
}

interface MiniAvatarProps {
  kit: string;
  accent: string;
  skin: string;
  hair: string;
  hairStyle: string;
  number: string;
  size: number;
}

/**
 * Inline V3-style avatar — mirrors src/components/moments/cards/V3Avatar.tsx
 * but rendered as plain SVG so the preview page can SSR without pulling
 * the full satori pipeline.
 */
function MiniAvatar({ kit, accent, skin, hair, hairStyle, number, size }: MiniAvatarProps) {
  const HAIR_PATHS: Record<string, string> = {
    short: 'M 30 38 Q 32 22 50 22 Q 68 22 70 38 Q 65 26 50 26 Q 35 26 30 38 Z',
    tall: 'M 28 40 Q 30 14 50 14 Q 70 14 72 40 Q 65 24 50 24 Q 35 24 28 40 Z',
    shaved: '',
    cap: 'M 28 38 L 28 30 Q 28 18 50 18 Q 72 18 72 30 L 72 38 Q 65 30 50 30 Q 35 30 28 38 Z',
  };
  const hairD = HAIR_PATHS[hairStyle] ?? HAIR_PATHS.short;

  return (
    <div
      style={{
        position: 'relative',
        width: size,
        height: size,
        borderRadius: size / 2,
        background: PALETTE.cream,
        border: `${size > 200 ? 3 : 2}px solid ${PALETTE.ink}`,
        overflow: 'hidden',
      }}
    >
      <svg width={size} height={size} viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
        <path d="M 8 100 Q 12 70, 32 62 Q 50 72, 68 62 Q 88 70, 92 100 Z" fill={kit} />
        <path d="M 40 64 L 50 76 L 60 64" stroke={accent} strokeWidth="1.5" fill="none" />
        <rect x="43" y="52" width="14" height="14" fill={skin} />
        <circle cx="50" cy="40" r="20" fill={skin} />
        {hairD && <path d={hairD} fill={hair} />}
        <rect x="40" y="40" width="4" height="1.5" fill={PALETTE.ink} opacity="0.65" />
        <rect x="56" y="40" width="4" height="1.5" fill={PALETTE.ink} opacity="0.65" />
        <circle cx="50" cy={88} r={size * 0.055} fill={PALETTE.cream} stroke={accent} strokeWidth="1.5" />
      </svg>
      <div
        style={{
          position: 'absolute',
          top: size * 0.83,
          left: 0,
          width: '100%',
          textAlign: 'center',
          fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700,
          fontSize: size * 0.085,
          color: PALETTE.ink,
          lineHeight: 1,
        }}
      >
        {number || '0'}
      </div>
    </div>
  );
}

export default async function PreviewPage({ params }: PageProps) {
  const { token } = await params;

  const user = await prisma.user.findUnique({
    where: { walletAddress: token },
    include: {
      playerProfile: true,
      squads: {
        include: {
          squad: true,
        },
      },
    },
  });

  if (!user || user.chain !== 'preview') {
    notFound();
  }

  const profile = user.playerProfile;
  const squadMembership = user.squads[0];
  const squad = squadMembership?.squad;

  if (!squad) {
    notFound();
  }

  // Pull last session's per-player stats
  const lastSession = await prisma.match.findFirst({
    where: {
      OR: [{ homeSquadId: squad.id }, { awaySquadId: squad.id }],
      status: 'verified',
    },
    orderBy: { createdAt: 'desc' },
    include: {
      playerStats: {
        where: profile ? { profileId: profile.id } : undefined,
      },
    },
  });

  const playerStats = lastSession?.playerStats[0];

  const avatar = {
    kit: user.avatarKitColor ?? PALETTE.red,
    accent: user.avatarAccentColor ?? PALETTE.navy,
    skin: user.avatarSkinTone ?? '#c89e7c',
    hair: user.avatarHairColor ?? '#2a1a10',
    hairStyle: user.avatarHairStyle ?? 'short',
    number: user.avatarNumber ?? '',
  };

  const goals = playerStats?.goals ?? 0;
  const minutesPlayed = playerStats?.minutesPlayed ?? 0;
  const gamesPlayed = Math.max(1, Math.round(minutesPlayed / 7));

  return (
    <div
      style={{
        minHeight: '100vh',
        background: PALETTE.cream,
        padding: '40px 20px',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        color: PALETTE.ink,
      }}
    >
      <div style={{ maxWidth: 600, margin: '0 auto' }}>
        {/* Top ribbon */}
        <div style={{ display: 'flex', gap: 4, marginBottom: 28 }}>
          <div style={{ width: 28, height: 4, background: PALETTE.mustard }} />
          <div style={{ width: 28, height: 4, background: PALETTE.red }} />
          <div style={{ width: 28, height: 4, background: PALETTE.navy }} />
          <div style={{ width: 28, height: 4, background: PALETTE.sage }} />
        </div>

        {/* Identity line */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            marginBottom: 36,
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 12,
            fontWeight: 700,
            letterSpacing: '0.18em',
            textTransform: 'uppercase',
            color: PALETTE.navy,
          }}
        >
          <div style={{ width: 7, height: 7, borderRadius: 3.5, background: PALETTE.red }} />
          SportWarren · Preview
        </div>

        {/* Hello headline */}
        <h1
          style={{
            fontFamily: 'Antonio, Impact, sans-serif',
            fontSize: 72,
            fontWeight: 800,
            lineHeight: 0.95,
            margin: 0,
            letterSpacing: '-0.02em',
            textTransform: 'uppercase',
          }}
        >
          Hello {user.name?.split(' ')[0] ?? 'there'}.
        </h1>

        <p
          style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 15,
            lineHeight: 1.6,
            color: PALETTE.inkLight,
            marginTop: 18,
            marginBottom: 36,
            maxWidth: 520,
          }}
        >
          Your captain set you up on a new thing for the {squad.name} group.
          Last week's session is already in — your stats are below. Tap around,
          tweak your kit if you want, sim a match against the rest of the lads,
          see you next time.
        </p>

        {/* Twin card */}
        <div
          style={{
            background: PALETTE.cream,
            border: `2px solid ${PALETTE.ink}`,
            borderRadius: 12,
            padding: 28,
            display: 'flex',
            gap: 24,
            alignItems: 'center',
            marginBottom: 28,
          }}
        >
          <MiniAvatar {...avatar} size={140} />

          <div style={{ flex: 1, minWidth: 0 }}>
            <div
              style={{
                fontFamily: 'JetBrains Mono, monospace',
                fontSize: 10,
                fontWeight: 700,
                letterSpacing: '0.2em',
                textTransform: 'uppercase',
                color: PALETTE.navy,
                marginBottom: 6,
              }}
            >
              You · {user.position ?? 'No position set'}
            </div>
            <div
              style={{
                fontFamily: 'Antonio, Impact, sans-serif',
                fontSize: 36,
                fontWeight: 800,
                lineHeight: 1,
                marginBottom: 16,
                textTransform: 'uppercase',
                letterSpacing: '-0.01em',
              }}
            >
              {user.name}
            </div>

            {/* Inline stat band */}
            <div
              style={{
                background: PALETTE.ink,
                color: PALETTE.cream,
                padding: '10px 14px',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                gap: 12,
                borderLeft: `4px solid ${PALETTE.red}`,
              }}
            >
              <span
                style={{
                  fontFamily: 'JetBrains Mono, monospace',
                  fontSize: 22,
                  fontWeight: 700,
                }}
              >
                {goals}
              </span>
              <span
                style={{
                  fontFamily: 'JetBrains Mono, monospace',
                  fontSize: 9,
                  fontWeight: 700,
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase',
                  opacity: 0.85,
                }}
              >
                Goals · {gamesPlayed} games · last week
              </span>
            </div>
          </div>
        </div>

        {/* What this is */}
        <div
          style={{
            background: 'rgba(28,58,94,0.08)',
            border: `1px solid ${PALETTE.navy}`,
            padding: 20,
            borderRadius: 8,
            marginBottom: 28,
          }}
        >
          <div
            style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: '0.18em',
              textTransform: 'uppercase',
              color: PALETTE.navy,
              marginBottom: 8,
            }}
          >
            What this is
          </div>
          <p
            style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 13,
              lineHeight: 1.6,
              color: PALETTE.ink,
              margin: 0,
            }}
          >
            Every game leaves a mark. Your goals, the matches you played,
            who else was on — all preserved permanently. No more "wait, what
            was the score last week?" The session is the record. You own it.
          </p>
        </div>

        {/* CTAs */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <Link
            href={`/preview/${encodeURIComponent(token)}/customize`}
            style={{
              background: PALETTE.mustard,
              color: PALETTE.ink,
              padding: '16px 20px',
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 14,
              fontWeight: 700,
              letterSpacing: '0.1em',
              textTransform: 'uppercase',
              textAlign: 'center',
              border: `2px solid ${PALETTE.red}`,
              textDecoration: 'none',
              display: 'block',
            }}
          >
            Tweak my kit →
          </Link>

          <Link
            href={`/preview/${encodeURIComponent(token)}/sim`}
            style={{
              background: 'transparent',
              color: PALETTE.ink,
              padding: '16px 20px',
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 14,
              fontWeight: 700,
              letterSpacing: '0.1em',
              textTransform: 'uppercase',
              textAlign: 'center',
              border: `2px solid ${PALETTE.navy}`,
              textDecoration: 'none',
              display: 'block',
            }}
          >
            Sim a match vs the group →
          </Link>
        </div>

        {/* Footer */}
        <div
          style={{
            marginTop: 48,
            paddingTop: 24,
            borderTop: `1px solid rgba(58,58,58,0.2)`,
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 10,
            fontWeight: 600,
            letterSpacing: '0.2em',
            textTransform: 'uppercase',
            color: PALETTE.inkLight,
            display: 'flex',
            justifyContent: 'space-between',
          }}
        >
          <span>SPORTWARREN · {squad.shortName ?? deriveInitials(squad.name)}</span>
          <span>{squad.name}</span>
        </div>
      </div>
    </div>
  );
}
