/**
 * Preview landing — the page each pre-seeded kickabout player lands on.
 *
 *   /preview/<token>
 *
 * Renders the player's twin (avatar + last week's session stats) without
 * requiring wallet sign-in. The token is the player's User.walletAddress,
 * generated by scripts/seed-kickabout-session.ts. The page is the demo
 * surface — keeps the friction to zero, makes the wedge legible in the
 * first 5 seconds.
 *
 * If the token is invalid, we show a friendly empty state pointing back
 * to the main site.
 */

import React from 'react';
import { notFound } from 'next/navigation';
import { prisma } from '@/lib/db';
import Link from 'next/link';
import { MiniAvatar, PALETTE } from '../_components/MiniAvatar';


interface PageProps {
  params: Promise<{ token: string }>;
}

function deriveInitials(name: string): string {
  return name
    .split(/\s+/)
    .map((p) => p[0])
    .join('')
    .slice(0, 2)
    .toUpperCase();
}

export default async function PreviewPage({ params }: PageProps) {
  const { token } = await params;

  const user = await prisma.user.findUnique({
    where: { walletAddress: token },
    include: {
      playerProfile: true,
      squads: {
        include: {
          squad: true,
        },
      },
    },
  });

  if (!user || user.chain !== 'preview') {
    notFound();
  }

  const profile = user.playerProfile;
  const squadMembership = user.squads[0];
  const squad = squadMembership?.squad;

  if (!squad) {
    notFound();
  }

  // Pull last session's per-player stats
  const lastSession = await prisma.match.findFirst({
    where: {
      OR: [{ homeSquadId: squad.id }, { awaySquadId: squad.id }],
      status: 'verified',
    },
    orderBy: { createdAt: 'desc' },
    include: {
      playerStats: {
        where: profile ? { profileId: profile.id } : undefined,
      },
    },
  });

  const playerStats = lastSession?.playerStats[0];

  const avatar = {
    kit: user.avatarKitColor ?? PALETTE.red,
    accent: user.avatarAccentColor ?? PALETTE.navy,
    skin: user.avatarSkinTone ?? '#c89e7c',
    hair: user.avatarHairColor ?? '#2a1a10',
    hairStyle: user.avatarHairStyle ?? 'short',
    number: user.avatarNumber ?? '',
  };

  const goals = playerStats?.goals ?? 0;
  const minutesPlayed = playerStats?.minutesPlayed ?? 0;
  const gamesPlayed = Math.max(1, Math.round(minutesPlayed / 7));

  return (
    <div
      style={{
        minHeight: '100vh',
        background: PALETTE.cream,
        padding: '40px 20px',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        color: PALETTE.ink,
      }}
    >
      <div style={{ maxWidth: 600, margin: '0 auto' }}>
        {/* Top ribbon */}
        <div style={{ display: 'flex', gap: 4, marginBottom: 28 }}>
          <div style={{ width: 28, height: 4, background: PALETTE.mustard }} />
          <div style={{ width: 28, height: 4, background: PALETTE.red }} />
          <div style={{ width: 28, height: 4, background: PALETTE.navy }} />
          <div style={{ width: 28, height: 4, background: PALETTE.sage }} />
        </div>

        {/* Identity line */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            marginBottom: 36,
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 12,
            fontWeight: 700,
            letterSpacing: '0.18em',
            textTransform: 'uppercase',
            color: PALETTE.navy,
          }}
        >
          <div style={{ width: 7, height: 7, borderRadius: 3.5, background: PALETTE.red }} />
          SportWarren · Preview
        </div>

        {/* Hello headline */}
        <h1
          style={{
            fontFamily: 'Antonio, Impact, sans-serif',
            fontSize: 72,
            fontWeight: 800,
            lineHeight: 0.95,
            margin: 0,
            letterSpacing: '-0.02em',
            textTransform: 'uppercase',
          }}
        >
          Hello {user.name?.split(' ')[0] ?? 'there'}.
        </h1>

        <p
          style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 15,
            lineHeight: 1.6,
            color: PALETTE.inkLight,
            marginTop: 18,
            marginBottom: 36,
            maxWidth: 520,
          }}
        >
          Your captain set you up on a new thing for the {squad.name} group.
          Last week's session is already in — your stats are below. Tap around,
          tweak your kit if you want, sim a match against the rest of the lads,
          see you next time.
        </p>

        {/* Twin card */}
        <div
          style={{
            background: PALETTE.cream,
            border: `2px solid ${PALETTE.ink}`,
            borderRadius: 12,
            padding: 28,
            display: 'flex',
            gap: 24,
            alignItems: 'center',
            marginBottom: 28,
          }}
        >
          <MiniAvatar {...avatar} size={140} />

          <div style={{ flex: 1, minWidth: 0 }}>
            <div
              style={{
                fontFamily: 'JetBrains Mono, monospace',
                fontSize: 10,
                fontWeight: 700,
                letterSpacing: '0.2em',
                textTransform: 'uppercase',
                color: PALETTE.navy,
                marginBottom: 6,
              }}
            >
              You · {user.position ?? 'No position set'}
            </div>
            <div
              style={{
                fontFamily: 'Antonio, Impact, sans-serif',
                fontSize: 36,
                fontWeight: 800,
                lineHeight: 1,
                marginBottom: 16,
                textTransform: 'uppercase',
                letterSpacing: '-0.01em',
              }}
            >
              {user.name}
            </div>

            {/* Inline stat band */}
            <div
              style={{
                background: PALETTE.ink,
                color: PALETTE.cream,
                padding: '10px 14px',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                gap: 12,
                borderLeft: `4px solid ${PALETTE.red}`,
              }}
            >
              <span
                style={{
                  fontFamily: 'JetBrains Mono, monospace',
                  fontSize: 22,
                  fontWeight: 700,
                }}
              >
                {goals}
              </span>
              <span
                style={{
                  fontFamily: 'JetBrains Mono, monospace',
                  fontSize: 9,
                  fontWeight: 700,
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase',
                  opacity: 0.85,
                }}
              >
                Goals · {gamesPlayed} games · last week
              </span>
            </div>
          </div>
        </div>

        {/* What this is */}
        <div
          style={{
            background: 'rgba(28,58,94,0.08)',
            border: `1px solid ${PALETTE.navy}`,
            padding: 20,
            borderRadius: 8,
            marginBottom: 28,
          }}
        >
          <div
            style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: '0.18em',
              textTransform: 'uppercase',
              color: PALETTE.navy,
              marginBottom: 8,
            }}
          >
            What this is
          </div>
          <p
            style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 13,
              lineHeight: 1.6,
              color: PALETTE.ink,
              margin: 0,
            }}
          >
            Every game leaves a mark. Your goals, the matches you played,
            who else was on — all preserved permanently. No more "wait, what
            was the score last week?" The session is the record. You own it.
          </p>
        </div>

        {/* CTAs */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <Link
            href={`/preview/${encodeURIComponent(token)}/customize`}
            style={{
              background: PALETTE.mustard,
              color: PALETTE.ink,
              padding: '16px 20px',
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 14,
              fontWeight: 700,
              letterSpacing: '0.1em',
              textTransform: 'uppercase',
              textAlign: 'center',
              border: `2px solid ${PALETTE.red}`,
              textDecoration: 'none',
              display: 'block',
            }}
          >
            Tweak my kit →
          </Link>

          <Link
            href={`/preview/${encodeURIComponent(token)}/sim`}
            style={{
              background: 'transparent',
              color: PALETTE.ink,
              padding: '16px 20px',
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 14,
              fontWeight: 700,
              letterSpacing: '0.1em',
              textTransform: 'uppercase',
              textAlign: 'center',
              border: `2px solid ${PALETTE.navy}`,
              textDecoration: 'none',
              display: 'block',
            }}
          >
            Sim a match vs the group →
          </Link>
        </div>

        {/* Footer */}
        <div
          style={{
            marginTop: 48,
            paddingTop: 24,
            borderTop: `1px solid rgba(58,58,58,0.2)`,
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 10,
            fontWeight: 600,
            letterSpacing: '0.2em',
            textTransform: 'uppercase',
            color: PALETTE.inkLight,
            display: 'flex',
            justifyContent: 'space-between',
          }}
        >
          <span>SPORTWARREN · {squad.shortName ?? deriveInitials(squad.name)}</span>
          <span>{squad.name}</span>
        </div>
      </div>
    </div>
  );
}
